"""update  tables

Revision ID: 1ad72c78a7c8
Revises: ec93160de5ed
Create Date: 2025-04-06 16:48:02.970150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad72c78a7c8'
down_revision: Union[str, None] = 'ec93160de5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taskmodels_user_id_fkey', 'taskmodels', type_='foreignkey')
    op.create_foreign_key(None, 'taskmodels', 'usermodels', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('usermodels', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodels', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'taskmodels', type_='foreignkey')
    op.create_foreign_key('taskmodels_user_id_fkey', 'taskmodels', 'usermodels', ['user_id'], ['id'])
    # ### end Alembic commands ###
