"""initial talbe

Revision ID: 389cb771d297
Revises: 666ebe351814
Create Date: 2025-04-06 17:02:27.963490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389cb771d297'
down_revision: Union[str, None] = '666ebe351814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id',sa.BIGINT(),nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskmodels',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('is_complited', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodels.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskmodels_user_id'), 'taskmodels', ['user_id'], unique=False)
    op.create_table('remindermodels',
    sa.Column('scheduled_time', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['taskmodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remindermodels_task_id'), 'remindermodels', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remindermodels_task_id'), table_name='remindermodels')
    op.drop_table('remindermodels')
    op.drop_index(op.f('ix_taskmodels_user_id'), table_name='taskmodels')
    op.drop_table('taskmodels')
    op.drop_table('usermodels')
    # ### end Alembic commands ###
